services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_ADMINKA_GATEWAY_URL=${VITE_ADMINKA_GATEWAY_URL:-http://localhost:8080}
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: profession_web_app_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    command: |
      sh -c "
      echo 'Waiting for DATABASE...'
      until python - <<'PYEND'
      import os,sys
      import psycopg
      try:
          psycopg.connect(os.environ['DATABASE_URL'])
          sys.exit(0)
      except Exception:
          sys.exit(1)
      PYEND
      do sleep 2; echo '.'; done
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      exec python manage.py runserver 0.0.0.0:$${BACKEND_PORT:-8000}
      "
    networks:
      - app_network
    

volumes:
  postgres_data_profession:
  static_volume:
  media_volume:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge