# Generated by Django 5.2.12 on 2026-03-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_notificatio_user_id_427e4b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='html_message',
        ),
    ]
