from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path(
        'landing/courses/',
        views.CourseDTOList.as_view(),
        name='course-list-preview',
    ),
    path(
        'app/my-courses/',
        views.PurchasedCoursesView.as_view(),
        name='my-courses',
    ),
    path(
        'app/my-schedule/',
        views.MyScheduleView.as_view(),
        name='my-schedule',
    ),
    path(
        'app/courses/<slug:course_slug>/home/',
        views.CourseHomePageView.as_view(),
        name='course-homepage',
    ),
    path(
        'app/courses/', 
        views.CourseListView.as_view(),
        name='courses-list'
    ),
    path(
        'app/courses/<slug:slug>/',
        views.CourseDetailView.as_view(),
        name='courses-detail',
    ),
    path(
        'courses/<slug:course_slug>/sections/',
        views.SectionCreateView.as_view(),
        name='course-sections-list',
    ),
    path(
        'courses/<slug:course_slug>/sections/<slug:section_slug>/',
        views.SectionDetailView.as_view(),
        name='course-sections-detail',
    ),
    path(
        'courses/<slug:course_slug>/lessons/',
        views.LessonCreateView.as_view(),
        name='course-lessons-list',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/',
        views.LessonDetailView.as_view(),
        name='course-lessons-detail',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/',
        views.HomeworkCreateView.as_view(),
        name='lesson-homeworks-list',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/<slug:homework_slug>/tasks/<uuid:task_id>/',
        views.TaskDetailView.as_view(),
        name='homework-tasks-detail',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/<slug:homework_slug>/tasks/',
        views.TaskCreateView.as_view(),
        name='homework-tasks-list',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/<slug:homework_slug>/questions/<uuid:question_id>/',
        views.QuestionDetailView.as_view(),
        name='homework-questions-detail',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/<slug:homework_slug>/questions/',
        views.QuestionCreateView.as_view(),
        name='homework-questions-list',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/homeworks/<slug:homework_slug>/',
        views.HomeworkDetailView.as_view(),
        name='lesson-homeworks-detail',
    ),

    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/start/',
        views.WebinarStartView.as_view(),
        name='webinar-start',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/stop/',
        views.WebinarStopView.as_view(),
        name='webinar-stop',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/join/',
        views.WebinarJoinView.as_view(),
        name='webinar-join',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/recorder-join/',
        views.WebinarRecorderJoinView.as_view(),
        name='webinar-recorder-join',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/recording/start/',
        views.WebinarRecordingStartView.as_view(),
        name='webinar-recording-start',
    ),
    path(
        'courses/<slug:course_slug>/lessons/<slug:lesson_slug>/webinar/whiteboard-pdf/',
        views.WebinarWhiteboardPdfView.as_view(),
        name='webinar-whiteboard-pdf',
    ),
    path(
        'kinescope/drm-auth/',
        views.KinescopeDRMAuthView.as_view(),
        name='kinescope-drm-auth',
    ),
]
