# Generated by Django 6.0.1 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser',
                 models.BooleanField(default=False,
                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                     verbose_name='superuser status')),
                ('email', models.EmailField(blank=True,
                 max_length=254, verbose_name='email address')),
                ('is_staff',
                 models.BooleanField(default=False,
                                     help_text='Designates whether the user can log into this admin site.',
                                     verbose_name='staff status')),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active')),
                ('first_name', models.CharField(
                    blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email_cipher',
                 models.CharField(blank=True,
                                  db_index=True,
                                  error_messages={
                                      'unique': 'Пользователь с таким email уже существует'},
                                  help_text='Введите email',
                                  max_length=255,
                                  null=True,
                                  unique=True)),
                ('phone_cipher',
                 models.CharField(blank=True,
                                  db_index=True,
                                  error_messages={
                                      'unique': 'Пользователь с таким телефоном уже существует'},
                                  help_text='Введите телефон',
                                  max_length=100,
                                  null=True,
                                  unique=True)),
                ('password_hash', models.CharField(blank=True,
                 help_text='Введите пароль', max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('reset_token', models.CharField(blank=True,
                 db_index=True, max_length=100, null=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True,
                                        help_text='Specific permissions for this user.',
                                        related_name='user_set',
                                        related_query_name='user',
                                        to='auth.permission',
                                        verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
        ),
    ]
