# Generated by Django 6.0.2 on 2026-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_cipher',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'Пользователь с такой почтой уже существует'}, help_text='Введите email', max_length=255, null=True, unique=True),
        ),
    ]
