# Generated by Django 5.2.11 on 2026-02-19 08:22

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password_hash_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], null=True)),
                ('avatar', models.ImageField(blank=True, default='users/default_photo_user.png', null=True, upload_to=apps.users.models.profile_image_path, verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетная запись',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
