# Generated by Django 6.0.5 on 2026-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat_bot', '0003_chat_message_session_remove_chatmessage_chat_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Заголовок чата'),
        ),
    ]
