# Generated by Django 6.0.5 on 2026-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat_bot', '0004_alter_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context_summary',
            field=models.TextField(blank=True, default='', verbose_name='Сжатый контекст разговора'),
        ),
    ]
