# Generated by Django 6.0.2 on 2026-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность записи'),
        ),
    ]
