# Generated by Django 5.2.11 on 2026-02-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Курс в корзине', 'verbose_name_plural': 'Курсы в корзине'},
        ),
    ]
