# Generated by Django 6.0.2 on 2026-05-08 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0014_recalc_homework_max_points'),
        ('webinars', '0002_recording_duration_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('watched_ratio', models.FloatField(default=0.0, verbose_name='Доля просмотра от 0 до 1 (макс от live и записи)')),
                ('all_homeworks_submitted', models.BooleanField(default=False, verbose_name='Все ДЗ урока сданы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Урок пройден')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда впервые пройден')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогрессы по урокам',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='stats_lesso_user_id_f67f48_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='RecordingView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Уникально просмотрено секунд')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='Позиция остановки для resume')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='webinars.recording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр записи',
                'verbose_name_plural': 'Просмотры записей',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'recording')},
            },
        ),
        migrations.CreateModel(
            name='WebinarAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(verbose_name='Подключился')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Отключился')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Просмотрено секунд (агрегат)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_attendances', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Посещение вебинара',
                'verbose_name_plural': 'Посещения вебинаров',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'webinar'], name='stats_webin_user_id_a10d18_idx')],
            },
        ),
    ]
