# Generated by Django 6.0.3 on 2026-03-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Авторы курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='homework',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_courses', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='ID курса'),
        ),
        migrations.AddField(
            model_name='section',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section', verbose_name='ID секции'),
        ),
        migrations.AddField(
            model_name='task',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='users_homeworks_attempts',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework'),
        ),
        migrations.AddField(
            model_name='users_homeworks_attempts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users_questions_answers',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='courses.users_homeworks_attempts'),
        ),
        migrations.AddField(
            model_name='users_questions_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
        ),
        migrations.AddField(
            model_name='users_tasks_answers',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to='courses.users_homeworks_attempts'),
        ),
        migrations.AddField(
            model_name='users_tasks_answers',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['homework_number'], name='courses_hom_homewor_ed78c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasedcourse',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_number'], name='courses_que_questio_8747af_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_number'], name='courses_sec_section_e6ec3a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_number'], name='courses_les_lesson__b8f0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_number'], name='courses_tas_task_nu_4c830f_idx'),
        ),
        migrations.AddIndex(
            model_name='users_homeworks_attempts',
            index=models.Index(fields=['user', 'attempt_number'], name='courses_use_user_id_a6b97b_idx'),
        ),
        migrations.AddIndex(
            model_name='users_questions_answers',
            index=models.Index(fields=['question_answer_number'], name='courses_use_questio_c70b63_idx'),
        ),
        migrations.AddIndex(
            model_name='users_tasks_answers',
            index=models.Index(fields=['task_answer_number'], name='courses_use_task_an_38adfc_idx'),
        ),
    ]
