# Generated by Django 6.0.4 on 2026-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_webinar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date_time',
        ),
    ]
