# Generated by Django 5.2.11 on 2026-02-04 13:03

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.courses.models.course_image_path,
                verbose_name='Изображение курса'),
        ),
    ]
