# Generated by Django 6.0.2 on 2026-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_webinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kinescope_folder_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Kinescope folder id'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='kinescope_upload_status',
            field=models.CharField(choices=[('none', 'Нет загрузки'), ('pending', 'В очереди'), ('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='none', max_length=20, verbose_name='Статут загрузки в кинескоп'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='kinescope_video_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Kenescope video id'),
        ),
    ]
