# Generated by Django 5.2.11 on 2026-02-11 20:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['created_at'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 11, 20, 53, 59, 739392, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('correct_ans', models.CharField()),
                ('answer_options', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users_Homeworks_Attempts',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users_questions_answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('user_answer', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='courses.users_homeworks_attempts')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users_tasks_answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=20)),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to='courses.users_homeworks_attempts')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['homework_id'], name='courses_que_homewor_6e7bae_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['homework_id'], name='courses_tas_homewor_aaa8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='users_homeworks_attempts',
            index=models.Index(fields=['user_id', 'homework_id', 'status'], name='courses_use_user_id_87ce09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='users_homeworks_attempts',
            unique_together={('homework_id', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='users_questions_answers',
            index=models.Index(fields=['attempt_id', 'question_id'], name='courses_use_attempt_d78b30_idx'),
        ),
        migrations.AddIndex(
            model_name='users_tasks_answers',
            index=models.Index(fields=['attempt_id', 'task_id', 'task_status'], name='courses_use_attempt_dcd302_idx'),
        ),
    ]
