# Generated by Django 6.0.4 on 2026-04-14 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_lesson_date_time"),
        ("courses", "0005_lesson_document"),
    ]

    operations = []
