# Generated by Django 6.0.4 on 2026-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_merge_20260414_1651"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="users_homeworks_attempts",
            name="courses_use_user_id_a6b97b_idx",
        ),
        migrations.RemoveIndex(
            model_name="users_questions_answers",
            name="courses_use_questio_c70b63_idx",
        ),
        migrations.RemoveIndex(
            model_name="users_tasks_answers",
            name="courses_use_task_an_38adfc_idx",
        ),
        migrations.RemoveField(
            model_name="users_homeworks_attempts",
            name="homework",
        ),
        migrations.RemoveField(
            model_name="users_homeworks_attempts",
            name="user",
        ),
        migrations.RemoveField(
            model_name="users_tasks_answers",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="users_tasks_answers",
            name="task",
        ),
        migrations.DeleteModel(
            name="Users_questions_answers",
        ),
        migrations.DeleteModel(
            name="Users_Homeworks_Attempts",
        ),
        migrations.DeleteModel(
            name="Users_tasks_answers",
        ),
    ]
