# Generated by Django 6.0.2 on 2026-04-18 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_webinar_whiteboard_pdf_url"),
        ("courses", "0006_merge_20260414_1651"),
    ]

    operations = []
