# Generated by Django 5.2.11 on 2026-02-11 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sub_title',
            field=models.CharField(
                default=datetime.datetime(
                    2026,
                    2,
                    11,
                    21,
                    41,
                    56,
                    574145,
                    tzinfo=datetime.timezone.utc),
                max_length=200,
                verbose_name='Краткое описание курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название курса'),
        ),
    ]
