# Generated by Django 6.0.2 on 2026-04-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_merge_20260418_1218'),
        ('courses', '0007_remove_users_homeworks_attempts_courses_use_user_id_a6b97b_idx_and_more'),
    ]

    operations = [
    ]
