# Generated by Django 5.2.11 on 2026-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_sub_title_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', verbose_name='Описание курса'),
            preserve_default=False,
        ),
    ]
