# Generated by Django 5.2.11 on 2026-02-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('access_expires_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='purchases', to='courses.course')),
            ],
            options={
                'verbose_name': 'Купленный курс',
                'verbose_name_plural': 'Купленные курсы',
                'db_table': 'courses_by_user',
            },
        ),
    ]
