# Generated by Django 6.0.4 on 2026-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20260419_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество баллов за вопрос'),
        ),
    ]
