# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='yandex_vs_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yandex Vector Store ID'),
        ),
    ]
