# Generated by Django 6.0.2 on 2026-04-21 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_max_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='kinescope_upload_status',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='kinescope_video_id',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='recording_resource_id',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='recording_sid',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='whiteboard_pdf_url',
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('recording', 'Запись идет'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='recording', max_length=20)),
                ('resource_id', models.CharField(blank=True, max_length=256)),
                ('sid', models.CharField(blank=True, max_length=256)),
                ('recording_url', models.URLField(blank=True, verbose_name='Ссылка на запись')),
                ('whiteboard_pdf_url', models.URLField(blank=True, verbose_name='Ссылка на pdf доски')),
                ('kinescope_video_id', models.CharField(blank=True, max_length=64, verbose_name='Kenescope video id')),
                ('kinescope_upload_status', models.CharField(choices=[('none', 'Нет загрузки'), ('pending', 'В очереди'), ('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='none', max_length=20, verbose_name='Статут загрузки в кинескоп')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_recordings', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.webinar')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
