# Generated by Django 5.2.11 on 2026-02-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_purchasedcourse_payment_purchasedcourse_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
