# Generated by Django 6.0.2 on 2026-04-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_webinar_kinescope_upload_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='started_by',
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
    ]
