# Generated by Django 5.2.11 on 2026-02-20 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_purchasedcourse'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('access_expires_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='purchases', to='courses.course')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='purchased_courses', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='purchased_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купленный курс',
                'verbose_name_plural': 'Купленные курсы',
                'db_table': 'courses_by_user',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
