# Generated by Django 5.2.11 on 2026-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_purchasedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sub_title',
            field=models.CharField(max_length=75, verbose_name='Краткое описание курса'),
        ),
    ]
