# Generated by Django 5.2.12 on 2026-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название домашнего задания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения урока'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(verbose_name='Правильный ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество баллов за задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='users_homeworks_attempts',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в'),
        ),
        migrations.AlterField(
            model_name='users_homeworks_attempts',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='users_questions_answers',
            name='user_answer',
            field=models.CharField(max_length=120, verbose_name='Ответ пользователя'),
        ),
    ]
