# Generated by Django 6.0.5 on 2026-05-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_recalc_homework_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность курса (недели)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AddField(
            model_name='course',
            name='starts_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта курса'),
        ),
    ]
