# Generated by Django 5.2.12 on 2026-03-25 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_authors_course_last_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course_id',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('section_id', models.PositiveIntegerField(verbose_name='Номер секции')),
                ('title', models.CharField(max_length=120, verbose_name='Название секции')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='URL')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='ID курса')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['course_id', 'section_id'],
                'unique_together': {('course_id', 'section_id')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section', verbose_name='ID секции'),
        ),
    ]
