# Generated by Django 5.2.12 on 2026-03-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_lesson_course_id_section_lesson_section_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date_time'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проведения урока'),
        ),
    ]
