# Generated by Django 5.2.12 on 2026-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_lesson_course_id_section_lesson_section_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='users_tasks_answers',
            name='courses_use_attempt_dcd302_idx',
        ),
        migrations.RemoveField(
            model_name='users_questions_answers',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='users_tasks_answers',
            name='task_status',
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='users_tasks_answers',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в'),
        ),
        migrations.AddField(
            model_name='users_tasks_answers',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('reviewed', 'Оценено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users_homeworks_attempts',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('reviewed', 'Оценено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='users_tasks_answers',
            index=models.Index(fields=['attempt_id', 'task_id', 'status'], name='courses_use_attempt_9d1fc6_idx'),
        ),
    ]
