# Generated by Django 5.2.12 on 2026-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_gradedmixin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_questions_answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
