# Generated by Django 5.2.12 on 2026-03-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_users_questions_answers_is_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradedMixin',
        ),
    ]
