# Generated by Django 5.2.12 on 2026-03-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lesson_options_remove_lesson_date_and_more'),
        ('courses', '0019_delete_gradedmixin'),
    ]

    operations = [
    ]
