# Generated by Django 6.0.4 on 2026-04-17 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_remove_users_homeworks_attempts_courses_use_user_id_a6b97b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('reviewed', 'Оценено')], default='draft', max_length=20, verbose_name='Статус')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('grade', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Количество баллов')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('correct', 'Верно'), ('incorrect', 'Неверно'), ('partily', 'Частично верно')], max_length=20, null=True, verbose_name='Статус')),
                ('answer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('user_answer', models.CharField(blank=True, default='', max_length=120, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='homeworks.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('correct', 'Верно'), ('incorrect', 'Неверно'), ('partily', 'Частично верно')], max_length=20, null=True, verbose_name='Статус')),
                ('answer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('user_answer', models.TextField(blank=True, default='', verbose_name='Ответ пользователя')),
                ('points', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Баллы за задание')),
                ('teacher_comment', models.TextField(blank=True, default='', verbose_name='Комментарий преподавателя')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to='homeworks.attempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user'], name='homeworks_a_user_id_f0e853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('user', 'homework')},
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='taskanswer',
            unique_together={('attempt', 'task')},
        ),
    ]
