# Generated by Django 6.0.4 on 2026-05-06 10:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskanswer",
            name="points",
        ),
        migrations.RemoveField(
            model_name="taskanswer",
            name="teacher_comment",
        ),
        migrations.CreateModel(
            name="TaskReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1500,
                        null=True,
                        verbose_name="Комментарий преподавателя",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Выставленные баллы"
                    ),
                ),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="homeworks.taskanswer",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверяющий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ревью задания с развернутым ответом",
                "verbose_name_plural": "Ревью заданий с развернутым ответом",
                "ordering": ["-created_at"],
            },
        ),
    ]
