# Generated by Django 6.0.2 on 2026-05-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_add_task_review_reviewer_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда проверено'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил'),
        ),
    ]
